const events = [
	"La fête des voisins",
	"Une percée dans la forêt amazonienne",
	"Une retraite de 12 mois chez des moines tibétains",
	"Une visite de la morgue",
	"L'ordination diaconale de mon oncle intégriste",
	"L'arivée du réparateur Carglass",
	"Une pendaison publique à Kaboul",
	"Un meeting du Rassemblement National",
	"Un cours de peinture aquarelle",
	"Le voyage de classe au mémorial de Caen",
	"La visite du Palais de l'Elysée",
	"Un concours de beauté pour chien",
	"Une semaine au camping des Flots Bleus",
	"Un EVG à Amsterdam",
	"Un WE à la Fistinière",
	"L'enterrement de ma grand-mère",
	"La bataille de Stalingrad",
	"Une séance chez mon psy",
	"L'Aïd-el-Fitr",
	"Un entretien d'embauche à la DGSE",
	"La soirée de Noël au boulot",
	"La journée de Défense et Citoyenneté",
	"Mon discours d'investiture retransmis sur TF1",
	"Un suicide collectif de l'Ordre du Temple du Soleil",
	"Le passage de l'ouragan Tatiana",
	"Un 16ème de finale de Coupe de France de Football",
	"La salle d'attente d'un centre de dépistage VIH",
	"La vente aux enchères d'un Picasso période bleue",
	"Le défilé du 14 juillet",
	"Un dîner avec la belle famille",
	"Les 90 ans de Papy",
	"Les premières rencontres avec les extraterrestres",
	"la bar-mitzvah de mon neveu",
	"Le passage d'un barrage allemand en 1942",
	"Un meeting de tuning à Roubaix",
	"La douche collective après le match de rugby",
	"Le sommet du G8",
	"Une réunion projet sur le plan de transformation de 2025",
	"Les embouteillages d'un WE de chassé-croisé en Août",
	"La cellule de dégrisement",
	"La réunion des parents d'élèves",
	"La queue des toilettes femme en boîte de nuit",
	"Un camp scout",
	"L'épreuve de maths du baccalauréat",
	"Les 100 pas devant la salle d'accouchement",
	"L'ascension de l'Everest par la face nord",
	"L'université d'été du Parti Socialiste",
	"L'arrivée d'un bateau de migrants à Lampedusa",
	"Le cortège syndical du défilé du 1er Mai",
	"Les courses de Noël le 23 décembre à 19h00",
	"Une lune de miel à Venise",
	"Un date Tinder",
	"Le brunch du lendemin de mariage",
	"Le dépouillement des votes de l'élection municipale",
	"Une après-midi sur une plage naturiste au Cap d'Agde",
	"Le sommet sur la non-prolifération des armes nucléaires",
	"Une rave party dans le Cantal",
	"La cérémonie des 70 ans de la libération d'Auschwitz",
	"Le premier rendez-vous Pôle Emploi (France Travail pour les jeunes, ANPE pour les vieux)",
	"L'éclipse solaire du siècle",
	"La sortie des classes de la maternelle",
	"La pêche aux moules",
	"Un triste WE de Novembre où il pleut",
	"Le pélerinage de la Mecque",
	"10 heures de planque devant un repaire de narcos",
	"Une représentation du Lac des Cygnes à l'Opéra",
	"La contre-visite d'un appartement",
	"Une descente des flics dans les caves d'Aulnay-sous-bois",
	"Une opération à coeur ouvert",
	"Une partie-fin e chez la marquise",
	"Un examen de la prostate",
	"Un Paris-Abidjan en première classe",
	"Un McDo à 4 heures du matin",
	"Une balade au bois de Boulogne",
	"Le passage de la douane à l'aéroport JFK de New York",
	"Les vendanges dans le Bordelais",
	"Un concert de Julien Doré",
	"Un tournage Marc Dorcel",
	"Une battue aux sangliers en Sologne",
	"Le RDV chez le juge pour acter le divorce",
	"La finale de Question pour un Champion",
	"Le procès d'Emile Louis",
	"La Marche pour le climat",
	"Un 5 à 7 avec ma maîtresse",
	"Le Grand Prix de F1 de Monaco",
	"Un mariage à Beyrouth",
	"Un dîner de cons",
	"Le Vendée Globe",
	"L'essayage de la robe de mariée",
	"Un centre de réfugiés au Soudan du Sud"
];